use master;

create database FancyDressDB;

use FancyDressDB;

CREATE TABLE USERS (
	UserId INT PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(100) NOT NULL UNIQUE,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

select * from USERS;

CREATE TABLE Clothes (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	ImagePath NVARCHAR(255),
	Gender NVARCHAR(20),
	Size NVARCHAR(20)
);
SELECT * FROM Clothes WHERE 1=1;

CREATE TABLE Orders (
	Id INT PRIMARY KEY IDENTITY(1,1),
	CustomerName NVARCHAR(100) NOT NULL,
	CostumeId INT NOT NULL,
	Size NVARCHAR(10),
	OrderDate DATETIME DEFAULT GETDATE(),
	Status NVARCHAR(20) DEFAULT 'Pending',
	CustomerEmail NVARCHAR(150),
	FOREIGN KEY (CostumeId) REFERENCES Clothes(Id)
);
SELECT * FROM Orders;

CREATE TABLE Basket (
	Id INT PRIMARY KEY IDENTITY(1,1),
	CustomerName NVARCHAR(100) NOT NULL,
	CostumeId INT NOT NULL,
	Size NVARCHAR(10),
	Quantity INT DEFAULT 1, 
	AddedDate DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (CostumeId) REFERENCES Clothes(Id) ON DELETE CASCADE
);
SELECT * FROM Basket;

CREATE TABLE Likes (
	Id INT PRIMARY KEY IDENTITY(1,1),
	CustomerName NVARCHAR(100) NOT NULL,
	CostumeId INT NOT NULL,
	Size NVARCHAR(10),
	Quantity INT DEFAULT 1,
	FOREIGN KEY (CostumeId) REFERENCES Clothes(Id) ON DELETE CASCADE
);
SELECT * FROM Likes;



